### ISSUE TITLE
install_dev.sh cannot complete due to maven test failure

### ISSUE THREAD

**Issue by reilly3000** [dessalines/flowchat#156]
I was unable to get flowchat running on Ubuntu 17.10 using install_dev.sh due to the following test failure:

~/flowchat$ sudo bash install_dev.sh
yarn install v1.5.1
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.86s.
 10% building modules 5/6 modules 1 active ...ome/chris/flowchat/ui/src/styles.scssWarning: Can't resolve all parameters for NG2WebSocket in /home/chris/flowchat/ui/src/app/services/ng2-websocket.ts: (?, ?, ?). This will become an error in Angular v6.x
Warning: Can't resolve all parameters for NG2WebSocket in /home/chris/flowchat/ui/src/app/services/ng2-websocket.ts: (?, ?, ?). This will become an error in Angular v6.x
Date: 2018-03-29T15:34:11.452Z
Hash: c379cb9d0929df35cb61
Time: 18889ms
chunk {inline} inline.bundle.js, inline.bundle.js.map (inline) 3.89 kB [entry] [rendered]
chunk {main} main.bundle.js, main.bundle.js.map (main) 972 kB [initial] [rendered]
chunk {scripts} scripts.bundle.js, scripts.bundle.js.map (scripts) 65.7 kB [initial] [rendered]
chunk {styles} styles.bundle.js, styles.bundle.js.map (styles) 225 kB [initial] [rendered]
chunk {vendor} vendor.bundle.js, vendor.bundle.js.map (vendor) 3.53 MB [initial] [rendered]
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building flowchat 0.4.0
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ flowchat ---
[INFO] Deleting /home/chris/flowchat/service/target
[INFO]
[INFO] --- properties-maven-plugin:1.0-alpha-2:write-project-properties (default) @ flowchat ---
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ flowchat ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 42 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ flowchat ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 35 source files to /home/chris/flowchat/service/target/classes
[INFO] /home/chris/flowchat/service/src/main/java/com/chat/db/Actions.java: Some input files use unchecked or unsafe operations.
[INFO] /home/chris/flowchat/service/src/main/java/com/chat/db/Actions.java: Recompile with -Xlint:unchecked for details.
[INFO]
[INFO] >>> activejdbc-instrumentation:1.4.11:instrument (default) > process-classes @ flowchat >>>
[INFO]
[INFO] --- properties-maven-plugin:1.0-alpha-2:write-project-properties (default) @ flowchat ---
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ flowchat ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 42 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ flowchat ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] <<< activejdbc-instrumentation:1.4.11:instrument (default) < process-classes @ flowchat <<<
[INFO]
[INFO]
[INFO] --- activejdbc-instrumentation:1.4.11:instrument (default) @ flowchat ---
**************************** START INSTRUMENTATION ****************************
Directory: /home/chris/flowchat/service/target/classes
Instrumented class: /home/chris/flowchat/service/target/classes/com/chat/db/Tables$User.class
Instrumented class: /home/chris/flowchat/service/target/classes/com/chat/db/Tables$CommunityNoTextView.class
Instrumented class: /home/chris/flowchat/service/target/classes/com/chat/db/Tables$DiscussionNoTextView.class
Instrumented class: /home/chris/flowchat/service/target/classes/com/chat/db/Tables$CommunityRole.class
Instrumented class: /home/chris/flowchat/service/target/classes/com/chat/db/Tables$Community.class
Instrumented class: /home/chris/flowchat/service/target/classes/com/chat/db/Tables$UserSetting.class
Instrumented class: /home/chris/flowchat/service/target/classes/com/chat/db/Tables$CensoredWord.class
Instrumented class: /home/chris/flowchat/service/target/classes/com/chat/db/Tables$DiscussionTag.class
Instrumented class: /home/chris/flowchat/service/target/classes/com/chat/db/Tables$RankingConstants.class
Instrumented class: /home/chris/flowchat/service/target/classes/com/chat/db/Tables$DiscussionFullView.class
Instrumented class: /home/chris/flowchat/service/target/classes/com/chat/db/Tables$DiscussionUserView.class
Instrumented class: /home/chris/flowchat/service/target/classes/com/chat/db/Tables$UserAuditView.class
Instrumented class: /home/chris/flowchat/service/target/classes/com/chat/db/Tables$CommunityUserView.class
Instrumented class: /home/chris/flowchat/service/target/classes/com/chat/db/Tables$CommunityTag.class
Instrumented class: /home/chris/flowchat/service/target/classes/com/chat/db/Tables$UserView.class
Instrumented class: /home/chris/flowchat/service/target/classes/com/chat/db/Tables$CommunityRank.class
Instrumented class: /home/chris/flowchat/service/target/classes/com/chat/db/Tables$DiscussionRank.class
Instrumented class: /home/chris/flowchat/service/target/classes/com/chat/db/Tables$Tag.class
Instrumented class: /home/chris/flowchat/service/target/classes/com/chat/db/Tables$Login.class
Instrumented class: /home/chris/flowchat/service/target/classes/com/chat/db/Tables$CommunityAuditView.class
Instrumented class: /home/chris/flowchat/service/target/classes/com/chat/db/Tables$CommunityUser.class
Instrumented class: /home/chris/flowchat/service/target/classes/com/chat/db/Tables$CommunityView.class
Instrumented class: /home/chris/flowchat/service/target/classes/com/chat/db/Tables$CommentBreadcrumbsView.class
Instrumented class: /home/chris/flowchat/service/target/classes/com/chat/db/Tables$CommentTree.class
Instrumented class: /home/chris/flowchat/service/target/classes/com/chat/db/Tables$DiscussionUser.class
Instrumented class: /home/chris/flowchat/service/target/classes/com/chat/db/Tables$CommentRank.class
Instrumented class: /home/chris/flowchat/service/target/classes/com/chat/db/Tables$FavoriteDiscussionUser.class
Instrumented class: /home/chris/flowchat/service/target/classes/com/chat/db/Tables$CommunityTagView.class
Instrumented class: /home/chris/flowchat/service/target/classes/com/chat/db/Tables$DiscussionRole.class
Instrumented class: /home/chris/flowchat/service/target/classes/com/chat/db/Tables$FavoriteDiscussionUserView.class
Instrumented class: /home/chris/flowchat/service/target/classes/com/chat/db/Tables$DiscussionTagView.class
Instrumented class: /home/chris/flowchat/service/target/classes/com/chat/db/Tables$FullUser.class
Instrumented class: /home/chris/flowchat/service/target/classes/com/chat/db/Tables$Comment.class
Instrumented class: /home/chris/flowchat/service/target/classes/com/chat/db/Tables$TagsView.class
Instrumented class: /home/chris/flowchat/service/target/classes/com/chat/db/Tables$Discussion.class
Instrumented class: /home/chris/flowchat/service/target/classes/com/chat/db/Tables$CommentThreadedView.class
**************************** END INSTRUMENTATION ****************************
[INFO] Instrumentation: directory /home/chris/flowchat/service/target/test-classes does not exist, skipping
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ flowchat ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /home/chris/flowchat/service/src/test/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.3:testCompile (default-testCompile) @ flowchat ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 1 source file to /home/chris/flowchat/service/target/test-classes
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ flowchat ---
[INFO] Surefire report directory: /home/chris/flowchat/service/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running chat_websocket.chat_websocket.AppTest
java.io.FileNotFoundException: /home/chris/flowchat/service/flowchat.properties (No such file or directory)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:196)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:139)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:94)
        at com.chat.tools.Tools.loadProperties(Tools.java:113)
        at com.chat.DataSources.<clinit>(DataSources.java:21)
        at com.chat.tools.Tools.dbInit(Tools.java:58)
        at chat_websocket.chat_websocket.AppTest.setUp(AppTest.java:21)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
08:34:16.472 [main] WARN  org.javalite.activejdbc.DB - Could not close connection! MUST INVESTIGATE POTENTIAL CONNECTION LEAK!
org.javalite.activejdbc.DBException: cannot close connection 'default' because it is not available
        at org.javalite.activejdbc.DB.close(DB.java:263) [activejdbc-1.4.11.jar:na]
        at org.javalite.activejdbc.DB.close(DB.java:252) [activejdbc-1.4.11.jar:na]
        at com.chat.tools.Tools.dbClose(Tools.java:71) [classes/:na]
        at chat_websocket.chat_websocket.AppTest.tearDown(AppTest.java:26) [test-classes/:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:564) ~[na:na]
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47) [junit-4.11.jar:na]
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.11.jar:na]
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44) [junit-4.11.jar:na]
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33) [junit-4.11.jar:na]
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271) [junit-4.11.jar:na]
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70) [junit-4.11.jar:na]
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50) [junit-4.11.jar:na]
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238) [junit-4.11.jar:na]
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63) [junit-4.11.jar:na]
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236) [junit-4.11.jar:na]
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53) [junit-4.11.jar:na]
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229) [junit-4.11.jar:na]
        at org.junit.runners.ParentRunner.run(ParentRunner.java:309) [junit-4.11.jar:na]
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252) [surefire-junit4-2.12.4.jar:2.12.4]
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141) [surefire-junit4-2.12.4.jar:2.12.4]
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112) [surefire-junit4-2.12.4.jar:2.12.4]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:564) ~[na:na]
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189) [surefire-api-2.12.4.jar:2.12.4]
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165) [surefire-booter-2.12.4.jar:2.12.4]
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85) [surefire-booter-2.12.4.jar:2.12.4]
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115) [surefire-booter-2.12.4.jar:2.12.4]
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75) [surefire-booter-2.12.4.jar:2.12.4]
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.263 sec <<< FAILURE!
testEncrypt(chat_websocket.chat_websocket.AppTest)  Time elapsed: 0.128 sec  <<< ERROR!
java.lang.ExceptionInInitializerError
        at com.chat.tools.Tools.dbInit(Tools.java:58)
        at chat_websocket.chat_websocket.AppTest.setUp(AppTest.java:21)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: java.lang.NullPointerException
        at com.chat.tools.Tools.loadProperties(Tools.java:121)
        at com.chat.DataSources.<clinit>(DataSources.java:21)
        ... 32 more

Results :

Tests in error:
  testEncrypt(chat_websocket.chat_websocket.AppTest)

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.848 s
[INFO] Finished at: 2018-03-29T08:34:16-07:00
[INFO] Final Memory: 28M/94M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project flowchat: There are test failures.
[ERROR]
[ERROR] Please refer to /home/chris/flowchat/service/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
unzip:  cannot find or open target/flowchat.jar, target/flowchat.jar.zip or target/flowchat.jar.ZIP.
nohup: redirecting stderr to stdout

**Comment by dessalines** [comment]
You skipped a few steps for the instructions: https://github.com/dessalines/flowchat#edit-your-pomxml-file-to-point-to-your-database
